config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }

    resource :index
    root 'index#show'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]

    # I18n.available_locales
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end
end

app/controllers/index_controller.rb
# frozen_string_literal: true

class IndexController < ApplicationController
  def show; end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/index/show.html.erb
<nav class="navbar navbar-expand-sm fixed-top navbar-light">
  <div class="container">
    <a class="navbar-brand" href="#home">Brand</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar1">
            <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to t('index.home'), '#home', class: 'nav-link', id: 'home_link' %>
                </li>
                <li class="nav-item">
                  <%= link_to t('index.photos'), '#photos', class: 'nav-link', id: 'photos_link' %>
                </li>
                <li class="nav-item">
                  <%= link_to t('index.about'), '#about', class: 'nav-link', id: 'about_link' %>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown"><%= I18n.locale.to_s.upcase %></a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <% I18n.available_locales.each do |locale| %>
                    <%= link_to locale.to_s.upcase, root_path(locale: locale), class: 'dropdown-item' unless locale == I18n.locale %>
                  <% end %>
                  </div>
              </li>
              <li class="nav-item active">
                <% if current_user %>
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                <% else %>
                  <a class="nav-link" data-toggle="modal" data-target="#exampleModal"><%= t('index.sign_in') %></a>
                <% end %>
              </li>
            </ul>
        </div>
  </div>
</nav>
<main>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= form_for(User.new, url: new_session_path(:user), html: {id: 'sign_up_user', :'data-type' => 'json'}, remote: true) do |f| %>
          <div class="modal-body">
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control', placeholder: t('login_form.enter_email') %>
            </div>
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control', placeholder: t('login_form.password') %>
            </div>
            <!-- <div class="form-check"> -->
              <%#= f.check_box :remember_me, class: 'form-check-input' %>
              <%#= f.label :remember_me, class: 'form-check-label' %>
            <!-- </div> -->
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit 'Log in', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <section id="home" class="landing" onscroll="handleNavItems(this)">
    <h2 class="big-text"><%= t('photo_contest') %></h2>
  </section>
  <section id="photos" class="landing"></section>
  <section id="about" class="landing"></section>
</main>
<!-- <div class="intro">
  <div class="intro-text">
    <h1 class="hide">
      <span class="text">Creating inovation</span>
    </h1>
    <h1 class="hide">
      <span class="text">For Everyday</span>
    </h1>
    <h1 class="hide">
      <span class="text">people.</span>
    </h1>
  </div>
</div> -->
<!-- <div class="slider"></div> -->
<!-- <script>
  const tl = gsap.timeline({ defaults: { ease: "power1.out" } });

  tl.to(".text", { y: "0%", duration: 1, stagger: 0.25 });
  tl.to(".slider", { y: "-100%", duration: 1.5, delay: 0.5 });
  tl.to(".intro", { y: "-100%", duration: 1 }, "-=1.05");
  tl.fromTo("nav", { opacity: 0 }, { opacity: 1, duration: 1 });
  tl.fromTo(".big-text", { opacity: 0 }, { opacity: 1, duration: 1 }, "-=1");
</script> -->
<script>
  function handleNavItems(link) {
    var links = ['home_link', 'photos_link', 'about_link']

    for(var index = 0; index < links.length; index++) {
      document.getElementById(links[index]).className = 'nav-link'
    }
    link.className = 'nav-link active'
  }

  function isInViewport(el) {
    const rect = el.getBoundingClientRect();
    return (
      rect.top >= 0 &&
      rect.left >= 0 &&
      rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
      rect.right <= (window.innerWidth || document.documentElement.clientWidth)
    )
  }

  function checkViewport() {
    var home = document.getElementById('home')
    var photos = document.getElementById('photos')
    var about = document.getElementById('about')

    if (isInViewport(home)) {
      handleNavItems(document.getElementById('home_link'))
    } else if (isInViewport(photos)) {
      handleNavItems(document.getElementById('photos_link'))
    } else if (isInViewport(about)) {
      handleNavItems(document.getElementById('about_link'))
    }
  }

  function changeLanguage(language) {
    console.log(language.value);
    document.getElementById('language').submit()
  }

  window.addEventListener('load', (event) => {
    checkViewport()
  })

  window.addEventListener('scroll', (event) => {
    checkViewport()
  })

  // $('#exampleModal').on('shown.bs.modal', function () {
  //   $('#myInput').trigger('focus')
  // })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoContest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link
      href="https://fonts.googleapis.com/css2?family=Heebo:wght@500;700&family=Libre+Baskerville&display=swap"
      rel="stylesheet"
    />
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>